name = "masters_thesis"
uuid = "831534a0-f0d5-454b-aa8e-9ab4d65024ab"
authors = ["Peter Tkatchenko <peteratkatchenko@gmail.com>"]
version = "0.1.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
